config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/reply_booking', to: 'bookings#reply_rent'
  get '/renter_bookings', to: 'bookings#renter_bookings'

  resources :cats do
    resources :bookings, only: %i[new create]
  end
  get '/my_cats', to: 'cats#users_cats'
  resources :cats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :cat
end

app/models/cat.rb
class Cat < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cats, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :post_code, :phone_number, :email, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :post_code, :phone_number, :email, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
    @cat = Cat.find(params[:cat_id])
  end

  def create
    @cat = Cat.find(params[:cat_id])
    @user = current_user
    @booking = Booking.new(booking_params)
    @booking.cat_id = @cat.id
    @booking.user_id = @user.id
    if @booking.save!
      redirect_to renter_bookings_path(@cat)
    else
      render :new
    end
  end

  def renter_bookings
    @bookings = Booking.all
  end

  def booking_params
    params.require(:booking).permit(:date_to, :date_from, :cat_id, :status, :format)
  end

  def reply_rent
    @booking = Booking.find(params[:format])
    @booking.rent_status = params[:status]
    @booking.save
    redirect_to renter_bookings_path, notice: "Rent status change to #{params[:status]}"
  end

  # def reject_rent
  #   @cat = Cat.find[params[:id]]
  #   @cat.rent_status = 'rejected'
  #   redirect_to renter_bookings_path(@cat), notice: "Rent status change to Rejected"
  # end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @cats = Cat.where("breed ILIKE ?", "%#{params[:query]}%")
    else
      @cats = Cat.all
    end
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user = current_user
    if @cat.save!
      redirect_to my_cats_path(@cat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.new
    @cat = Cat.find(params[:id])
  end

  def edit
  end

  def update
    @cat.update(cat_params)
    redirect_to cat_path(@cat)
  end

  def users_cats
    @cats = Cat.where(user: current_user)
  end

  def destroy
    @cat.destroy
    redirect_to my_cats_path, status: :see_other
  end

  private

  def set_cat
    @cat = Cat.find(params[:id])
  end

  def cat_params
    params.require(:cat).permit(:name, :breed, :age, :description, photos: [])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <h1>Create your booking with the adorable <%= @cat.name %></h1>

<%= simple_form_for [@cat, @booking] do |f| %>
  <%= f.input :date_from, as: :date, html5: true%>
  <%= f.input :date_to, as: :date, html5: true %>
  <%= f.button :submit, class: "btn btn-flat" %>
<% end %>

app/views/bookings/renter_bookings.html.erb
<div class="container my-bookings">
  <h1 class="booking-h1">Here are your fluff ball bookings</h1>
<br> <br>
  <% @bookings.each do |booking| %>
    <div class="card-product-cat mb-4">
      <div class="cat-booking-image">
        <% @cat = Cat.find(booking.cat_id) %>
        <%= cl_image_tag @cat.photos.first.key %>
      </div>
      <div class="details pt-5 bg.light w-100">
      <% if current_user.id == booking.cat.user.id %>
        <p><%="Rental period: #{booking.date_from} - #{booking.date_to}"%></p>
        <p><%="Cat name: #{@cat.name} "%></p>
        <p><%="Cat renter: #{booking.user.first_name} #{booking.user.last_name} "%></p>
        <p><%= "Rental Status: #{booking.rent_status}"%></p>
      <% if booking.rent_status == "accepted" %>
        <p><strong>You approved this booking</strong></p>
        <%= link_to "Reject this booking", reply_booking_path(booking, status: 'rejected'), class: "btn btn-danger"%>
      <% elsif booking.rent_status == "rejected" %>
        <p><strong>You rejected this booking</strong></p>
        <%= link_to "Approve this booking", reply_booking_path(booking, status: 'accepted'), class: "btn btn-primary" %>
        <% else %>
          <%= link_to "Approve", reply_booking_path(booking, status: 'accepted'), class: "btn btn-primary" %>
          <%= link_to "Reject", reply_booking_path(booking, status: 'rejected'), class: "btn btn-danger" %>
      <% end %>

      <% else %>
        <p><%="Rental period: #{booking.date_from} - #{booking.date_to}"%></p>
        <p><%="Cat name: #{@cat.name} "%></p>
        <p><%="Cat owner: #{@cat.user.first_name} #{@cat.user.last_name} "%></p>
        <p><%="Cat renter: #{booking.user.first_name} #{booking.user.last_name} "%></p>
        <p><%= "Rental Status: #{booking.rent_status}"%></p>
      <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/cats/edit.html.erb
<div class="container">
  <%= simple_form_for @cat do |f| %>
    <%= f.input :name %>
    <%= f.input :breed %>
    <%= f.input :age %>
    <%= f.input :description %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/cats/index.html.erb
<div class="container">

  <div>
    <div class="index-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= asset_path("pair-cats-cuddling.jpg") %>');">
    <h1 class="index-heading">Browse cats</h1>
    <%= form_tag cats_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search breed"
      %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
  <%# <% @cats.each do |cat| %>
    <%# <li><%= link_to cat.name, cat_path(cat) %>
  <%# <% end %>
  <%= render 'shared/cards_index' %>
</div>

app/views/cats/new.html.erb
<div class="row justify-content-center">
  <div class="col-sm-6 mx-auto">

    <div class="container new-cat">
      <h1 colour>Add your cat</h1>

    <%= simple_form_for @cat do |f| %>
      <%= f.input :name %>
      <%= f.input :breed %>
      <%= f.input :age %>
      <%= f.input :description %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.button :submit, class: "btn btn-info" %>
    <% end %>
  </div>
</div>

app/views/cats/show.html.erb
  <div class="sessions d-flex body">
    <div class="container">
      <div class="container-carousel">
        <% if @cat.photos.size == 1 %>
          <%=cl_image_tag @cat.photos.first.key, class:"d-block w-100 image-height" %>
        <% else %>
          <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <% @cat.photos.each_with_index do |photo, index| %>
                <div data-bs-interval="2000" class="carousel-item <%= index == 0 ? "active" : '' %> ">
                  <%= cl_image_tag photo.key, class:"d-block w-100 image-height" %>
            </div>
              <% end %>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
      </div>
        <% end %>
        <div class="container mt-3 text-center cat-data-card">
          <h2>This is <%= @cat.name %></h2>
          <p><strong>Breed:</strong> <%= @cat.breed %></p>
          <p><strong>Age: </strong> <%= @cat.age %></p>
          <p><strong>Description: </strong> <%= @cat.description %></p>
          <p><strong>Cat owner: </strong><%= "#{@cat.user.first_name} #{@cat.user.last_name}"  %></p>
        </div>
    </div>
    </div>

    <div class="container booking-calendar">
      <h1>Create your booking with the adorable <%= @cat.name %></h1>
        <%= simple_form_for [@cat, @booking] do |f| %>
          <%= f.input :date_from, as: :date, html5: true %>
          <%= f.input :date_to, as: :date, html5: true %>
          <%= f.button :submit, class: "orange-button" %>
        <% end %>
    </div>
  </div>

app/views/cats/users_cats.html.erb
<div class="container">
  <h1>My Cat Listings</h1>
  <% @cats.each do |cat| %>
    <%= link_to cat_path(cat), class: "text-decoration-none" do %>
      <div class="card-product mt-5">
        <div class="desc-container">
          <%= cl_image_tag cat.photos.first.key %>
          <div class="container mt-5">
          <h2><%= cat.name %></h2>
          <p><%= cat.description %></p>
          <%= link_to "Edit", edit_cat_path(cat), class:"text-decoration-none btn-flat" %>
          <%= link_to "Delete", cat_path(cat), class:"text-decoration-none btn-flat", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rent-A-Cat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,400;0,700;1,400&family=Quattrocento+Sans:wght@400;700&family=Quicksand:wght@400;700&display=swap" rel="stylesheet">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>

  <body>
    <div class="page-container">
      <div class="navbar-container"><%= render "shared/navbar" %></div>
      <br>
      <div class="content-container"><%= yield %></div>
      <%# <div class="space"></div> %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="footer-container"><%= render "shared/footer" %></div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <%= render 'shared/home_banner' %>

  <%= render 'shared/register_banner' %>
  <%= render 'shared/cards' %>
  </div>
</div>

app/views/shared/_cards.html.erb
<br>
<div style="text-align: center">
  <h2>Hot puss!</h2>
</div>

<div class="cards">
  <% @cats.first(4).each do |cat| %>
    <%= link_to cat_path(cat), :class => "text-decoration-none" do %>
      <div class="card-cat">
        <%= cl_image_tag cat.photos[0].key %>
        <div class="card-cat-infos">
          <div>
            <h2><%= cat.name %></h2>
            <p><%= cat.description %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_cards_index.html.erb
<div class="container">
  <div class="cards-index">
    <% @cats.each do |cat| %>
      <%= link_to cat_path(cat), :class => "text-decoration-none" do %>
          <div class="card-cat-index">
            <%= cl_image_tag cat.photos[0].key %>
            <div class="card-cat-infos-index">
              <div>
                <h2><%= cat.name %></h2>
                <p><%= cat.description %></p>
              </div>
            </div>
          </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <%# <div class="container"> %>
    <div class="footer-links">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>
    <div class="footer-copyright">
      © We <i class="fas fa-heart"></i> pussies!
    </div>
  <%# </div> %>
</div>

app/views/shared/_home_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= asset_path("main_banner.jpg") %>');">
  <div class="container">
    <h1>Hire a cat!</h1>
    <p>Come find a feline friend to look after</p>
    <%= link_to "Show me the cats", cats_path, class: "btn-flat text-decoration-none" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <div class="logo">
      <%= link_to cats_path, class: "navbar-brand" do %>
        <%# <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
        <i class="fa-solid fa-cat red"></i>
        <h2 class="site-name">Rent-a-Cat</h2>
      <% end %>
    </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="navbar-btn-container">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <ul class="navbar-nav">
          <%= link_to "List your cat", new_cat_path, class: "nav-link" %>
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "My cats", my_cats_path, class: "dropdown-item" %>
                <%= link_to "My bookings", renter_bookings_path, class: "dropdown-item" %>
                <%= link_to "My account", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </li>
          <% else %>
            <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
          <% end %>
        </ul>
    </div>
  </div>
</div>

app/views/shared/_new.html.erb
<div class="container">
  <h1>Create your booking with the adorable <%= @cat.name %></h1>

<%= simple_form_for [@cat, @booking] do |f| %>
  <%= f.input :date_from, as: :date, html5: true%>
  <%= f.input :date_to, as: :date, html5: true %>
  <%= f.button :submit, class: "btn btn-flat" %>
<% end %>

app/views/shared/_register_banner.html.erb
<div class="reg_banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= asset_path("cat_banner.jpg") %>');">
  <div class="container" style="padding-left :160px">
    <h1>Register to list your cat</h1>
    <p>Every cat needs someone to feed them</p>
    <%= link_to "Register", new_user_registration_path, class: "btn-flat text-decoration-none" %>
  </div>
</div>